server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/qianshe_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: root
    password: qianshe_password
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: qianshe_password
      database: 0
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

sa-token:
  token-name: Authorization
  timeout: 2592000             # token有效期（秒）：30天
  active-timeout: 1800         # 临时有效期（秒）：30分钟
  is-concurrent: true          # 是否允许同一账号多地同时登录
  is-share: false             # 多人登录同一账号时是否共享token
  token-style: uuid           # token风格
  token-prefix: ""            # 不使用token前缀
  is-log: true               # 输出操作日志
  is-read-cookie: false       # 不从cookie中读取token
  is-read-head: true          # 从请求头读取token
  is-print: false            # 不打印版本字符画
  # Redis配置
  alone-redis:
    # 使用与spring.data.redis相同的配置
    database: ${spring.data.redis.database}
    host: ${spring.data.redis.host}
    port: ${spring.data.redis.port}
    password: ${spring.data.redis.password}
    timeout: ${spring.data.redis.timeout}
    lettuce:
      pool:
        min-idle: ${spring.data.redis.lettuce.pool.min-idle}
        max-idle: ${spring.data.redis.lettuce.pool.max-idle}
        max-active: ${spring.data.redis.lettuce.pool.max-active}
        max-wait: ${spring.data.redis.lettuce.pool.max-wait}

# 日志配置
logging:
  level:
    root: INFO
    com.qianshe.auth: INFO
    cn.dev33.satoken: INFO

# knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn 